# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# on-focused-monitor-changed = ['move-mouse window-force-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Cmd+h weird thing macos does
automatically-unhide-macos-hidden-apps = false

# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.main.binding]

cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

alt-s = 'layout accordion horizontal vertical' 
alt-e = 'layout tiles horizontal vertical' 

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating left'
alt-left = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating down'
alt-down = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating up'
alt-up = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating right'
alt-right = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating right'

alt-shift-h = 'move left'
alt-shift-left = 'move left'
alt-shift-j = 'move down'
alt-shift-down = 'move down'
alt-shift-k = 'move up'
alt-shift-up = 'move up'
alt-shift-l = 'move right'
alt-shift-right = 'move right'

alt-f = 'fullscreen'

alt-shift-space = 'layout floating tiling'

alt-o = 'focus-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-t = 'workspace T'
alt-w = 'workspace W'
alt-m = 'workspace M'
alt-b = 'workspace B'
alt-p = 'workspace P'
alt-a = 'workspace A'

alt-shift-t = 'move-node-to-workspace --focus-follows-window T'
alt-shift-w = 'move-node-to-workspace --focus-follows-window W'
alt-shift-m = 'move-node-to-workspace --focus-follows-window M'
alt-shift-b = 'move-node-to-workspace --focus-follows-window B'
alt-shift-p = 'move-node-to-workspace --focus-follows-window P'
alt-shift-a = 'move-node-to-workspace --focus-follows-window A'

# Applications
alt-enter = "exec-and-forget open -na Alacritty"
alt-shift-enter = "exec-and-forget open -na 'Brave Browser'"
alt-shift-n = "exec-and-forget open -a Finder"
alt-c = "exec-and-forget open 'x-apple.systempreferences:com.apple.preference.security'"
alt-shift-q = "close --quit-if-last-window"

alt-shift-r = "reload-config"
alt-r = "mode resize"

[mode.resize.binding]
    j = 'resize height +50'
    up = 'resize height +50'
    k = 'resize height -50'
    down = 'resize height -50'
    l = 'resize width +50'
    left = 'resize width +50'
    h = 'resize width -50'
    right = 'resize width -50'
    enter = 'mode main'
    esc = 'mode main'

[gaps]
    inner.horizontal = 5
    inner.vertical = 5
    outer.left =       2
    outer.bottom =     2
    outer.top =        2
    outer.right =      2

# Ensure workspaces are created on different monitors
[workspace-to-monitor-force-assignment]
    A = 1
    T = 2                            
    W = 3
    M = 3
    B = 3                            
    P = 3

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace --focus-follows-window W'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace --focus-follows-window W'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace --focus-follows-window W'

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace --focus-follows-window W'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace --focus-follows-window W'

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace --focus-follows-window T'

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace --focus-follows-window B'

[[on-window-detected]]
if.app-id = 'org.jkiss.dbeaver.core.product'
run = 'move-node-to-workspace --focus-follows-window B'

[[on-window-detected]]
if.app-id = 'com.microsoft.StorageExplorer'
run = 'move-node-to-workspace --focus-follows-window B'

[[on-window-detected]]
if.app-id = 'com.apple.dt.Xcode'
run = 'move-node-to-workspace --focus-follows-window M'

[[on-window-detected]]
if.app-id = 'com.google.android.studio'
run = 'move-node-to-workspace --focus-follows-window M'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace --focus-follows-window A'

[[on-window-detected]]
if.app-id = 'org.qgis.qgis3'
run = 'move-node-to-workspace --focus-follows-window A'

[[on-window-detected]]
if.app-id = 'org.qgis.qgis3'
run = 'move-node-to-workspace --focus-follows-window A'

[[on-window-detected]]
if.app-id = 'org.blenderfoundation.blender'
run = 'move-node-to-workspace --focus-follows-window A'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace --focus-follows-window A'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['layout floating', 'move-node-to-workspace --focus-follows-window A']

[[on-window-detected]]
if.app-id = 'net.ankiweb.dtop'
run = 'move-node-to-workspace --focus-follows-window P'

[[on-window-detected]]
if.app-id = 'com.vscodium'
run = 'move-node-to-workspace --focus-follows-window P'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace --focus-follows-window P'

[[on-window-detected]]
if.app-name-regex-substring = 'python3'
run = ['layout floating', 'move-node-to-workspace A']
