# Start AeroSpace at login
start-at-login = true

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse window-force-center']
on-focus-changed = ['move-mouse window-lazy-center']

# TODO: install sketcky bar
# TODO: install borders
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    # Install borders
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

[mode.main.binding]

    # Applications
    cmd-enter = "exec-and-forget open -na Alacritty"
    alt-shift-n = "exec-and-forget open /Users/alba"
    alt-shift-s = "exec-and-forget open 'x-apple.systempreferences:com.apple.preference.security'"
    alt-n = "exec-and-forget open -a Notes"
    cmd-shift-q = "close --quit-if-last-window"

    # Focus
    # cmd-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors --ignore-floating down'
    cmd-down = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors --ignore-floating down'
    # cmd-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors --ignore-floating up'
    cmd-up = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors --ignore-floating up'
    # cmd-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors --ignore-floating right'
    cmd-right = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors --ignore-floating right'
    # cmd-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors --ignore-floating left'
    cmd-left = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors --ignore-floating left'

    # Move
    # TODO: it does not really let you move between displays
    alt-shift-j = 'move left'
    alt-shift-k = 'move down'
    alt-shift-l = 'move up'
    alt-shift-h = 'move right'
    alt-shift-left = 'move-node-to-workspace --wrap-around --focus-follows-window next'
    alt-shift-right = 'move-node-to-workspace --wrap-around --focus-follows-window prev'

    # Layout
    alt-f = 'fullscreen'
    alt-shift-space = 'layout floating tiling'

    # Workspaces
    # TODO: these should have letters asigned to them
    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 10'

    # Move to workspaces
    # TODO: these should have letters asigned to them
    # TODO: when something is moved to a workspace the mouse should move
    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    cmd-shift-7 = 'move-node-to-workspace 7'
    cmd-shift-8 = 'move-node-to-workspace 8'
    cmd-shift-9 = 'move-node-to-workspace 9'
    cmd-shift-0 = 'move-node-to-workspace 10'

    # Move between workspaces
    cmd-tab = 'workspace-back-and-forth'
    cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Config
    alt-shift-r = 'reload-config'
    alt-r = 'mode resize'

[gaps]
    inner.horizontal = 2
    inner.vertical =   2
    outer.left =       2
    outer.bottom =     2
    outer.top =        2
    outer.right =      2

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

# Ensure workspaces are created on different monitors
[workspace-to-monitor-force-assignment]
    1 = 1                            
    2 = 2
    3 = 3

# Disable group apps
# defaults write com.apple.dock expose-group-apps -bool true && killall Dock
# Disable displays have different spaces
# defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer
