# Run Sketchybar together with AeroSpace
after-startup-command = ['exec-and-forget sketchybar']
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
# Use stacked layout as default, tiling kinda sucks
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
on-focus-changed = ['move-mouse window-lazy-center']
automatically-unhide-macos-hidden-apps = false

########################################################
# Keybindings
########################################################

[mode.main.binding]

# Disable weird mac shortcuts :/
cmd-h = []
cmd-alt-h = [] 

# Layout
alt-s = 'layout accordion horizontal vertical' 
alt-e = 'layout tiles horizontal vertical' 
alt-f = 'fullscreen'
alt-shift-space = 'layout floating tiling'

# Focus
alt-h = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating left'
alt-left = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating down'
alt-down = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating up'
alt-up = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating right'
alt-right = 'focus --boundaries-action wrap-around-the-workspace --ignore-floating right'

# Window navigation
alt-shift-h = 'move left'
alt-shift-left = 'move left'
alt-shift-j = 'move down'
alt-shift-down = 'move down'
alt-shift-k = 'move up'
alt-shift-up = 'move up'
alt-shift-l = 'move right'
alt-shift-right = 'move right'

# Workspace navigation
alt-t = 'workspace T'
alt-w = 'workspace W'
alt-m = 'workspace M'
alt-b = 'workspace B'
alt-p = 'workspace P'
alt-c = 'workspace C'
alt-g = 'workspace G'

alt-shift-t = 'move-node-to-workspace --focus-follows-window T'
alt-shift-w = 'move-node-to-workspace --focus-follows-window W'
alt-shift-m = 'move-node-to-workspace --focus-follows-window M'
alt-shift-b = 'move-node-to-workspace --focus-follows-window B'
alt-shift-p = 'move-node-to-workspace --focus-follows-window P'
alt-shift-c = 'move-node-to-workspace --focus-follows-window C'
alt-shift-g = 'move-node-to-workspace --focus-follows-window G'

# Applications
alt-enter = "exec-and-forget open -na Alacritty"
alt-shift-enter = "exec-and-forget open -na 'Brave Browser'"
alt-shift-n = "exec-and-forget open -a Finder"
alt-shift-s = "exec-and-forget open 'x-apple.systempreferences:com.apple.preference.security'"
alt-shift-q = "close --quit-if-last-window"

# General
alt-shift-r = "reload-config"
alt-r = "mode resize"

########################################################
# Resize
########################################################

[mode.resize.binding]
    j = 'resize height +50'
    up = 'resize height +50'
    k = 'resize height -50'
    down = 'resize height -50'
    l = 'resize width +50'
    left = 'resize width +50'
    h = 'resize width -50'
    right = 'resize width -50'
    enter = 'mode main'
    esc = 'mode main'

[gaps]
    inner.horizontal =  5
    inner.vertical =    5
    outer.left =        2
    outer.bottom =      2
    outer.top =         2
    outer.right =       2

########################################################
# Workspaces
########################################################

# Ensure workspaces are created on different monitors
[workspace-to-monitor-force-assignment]
    C = 3
    T = 1                            
    W = 2
    M = 2
    B = 2                            
    P = 2
    G = 2

########################################################
# Web
########################################################

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace --focus-follows-window W'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace --focus-follows-window W'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace --focus-follows-window W'

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace --focus-follows-window W'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace --focus-follows-window W'

########################################################
# Terminal
########################################################

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace --focus-follows-window T'

########################################################
# Back
########################################################

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace --focus-follows-window B'

[[on-window-detected]]
if.app-id = 'org.jkiss.dbeaver.core.product'
run = 'move-node-to-workspace --focus-follows-window B'

[[on-window-detected]]
if.app-id = 'com.microsoft.StorageExplorer'
run = 'move-node-to-workspace --focus-follows-window B'

########################################################
# Mobile
########################################################

[[on-window-detected]]
if.app-id = 'com.apple.dt.Xcode'
run = 'move-node-to-workspace --focus-follows-window M'

[[on-window-detected]]
if.app-id = 'com.google.android.studio'
run = 'move-node-to-workspace --focus-follows-window M'

########################################################
# Comm
########################################################

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace --focus-follows-window C'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace --focus-follows-window C'

[[on-window-detected]]
if.app-name-regex-substring = 'python3'
run = ['layout floating', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['layout floating', 'move-node-to-workspace --focus-follows-window C']

########################################################
# GUI
########################################################

[[on-window-detected]]
if.app-id = 'org.qgis.qgis3'
run = 'move-node-to-workspace --focus-follows-window G'

[[on-window-detected]]
if.app-id = 'org.blenderfoundation.blender'
run = 'move-node-to-workspace --focus-follows-window G'

[[on-window-detected]]
if.app-id = 'com.vscodium'
run = 'move-node-to-workspace --focus-follows-window G'

[[on-window-detected]]
if.app-id = 'org.libreoffice.script'
run = 'move-node-to-workspace --focus-follows-window G'

[[on-window-detected]]
if.app-id = 'com.yourcompany.LibreCAD'
run = 'move-node-to-workspace --focus-follows-window G'

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = 'move-node-to-workspace --focus-follows-window G'

########################################################
# Personal
########################################################

[[on-window-detected]]
if.app-id = 'net.ankiweb.dtop'
run = 'move-node-to-workspace --focus-follows-window P'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace --focus-follows-window P'
